"""FLOW-Realm-CRUD: Full realm lifecycle with 8 datasource types.

Creates ONE schema with 8 datasources:
  DB: Postgres, MySQL, MariaDB, Oracle, Snowflake, Mongo
  File: CSV (S3), Excel (S3)

Fetches entities from each DS, builds schema graph, creates realm/fabric.
Then tests all realm + ingest stream endpoints.
"""

from flowlib.core import req, build_setup, build_collection, write_flow


def _db_ds(step, label, prefix, var_id, var_cat, critical=True):
    """DB datasource creation step."""
    p = prefix + "_" if prefix else ""
    fail = f"if(![200,201].includes(code)){{pm.collectionVariables.set('_flow_failed','true');pm.collectionVariables.set('_flow_failed_at','{step}');}}" if critical else ""
    return req(f"{step} Create {label} DS", "POST", "/datasource",
        [f"const code=pm.response.code;",
         f"pm.test('{step} {label} 2xx', () => {{ {fail} pm.expect(code).to.be.oneOf([200,201]); }});",
         "let b={}; try{b=pm.response.json();}catch(e){}",
         "const d=b.dataSourceModel||b.data||b;",
         f"if(d.id||d.sourceId) pm.collectionVariables.set('{var_id}', String(d.id||d.sourceId));",
         f"if(d.dataCatalogName) pm.collectionVariables.set('{var_cat}', d.dataCatalogName);",
         f"console.log('{label} DS id='+(d.id||d.sourceId));"],
        base="app_base_url",
        body={"name": f"pm-flow-{label.lower()}-" + "{{$timestamp}}",
              "driverType": "{{" + p + "driverType}}",
              "dbHostName": "{{" + p + "dbHost}}",
              "dbPort": "{{" + p + "dbPort}}",
              "databaseName": "{{" + p + "dbName}}",
              "dbUserName": "{{" + p + "dbUser}}",
              "dbPassword": "{{" + p + "dbPassword}}",
              "aesRandomIV": "{{" + p + "aesRandomIV}}",
              "dbSchema": "{{" + p + "dbSchema}}",
              "driverClassName": "{{" + p + "driverClassName}}",
              "deleted": False})


def generate():
    base = "app_base_url"

    ds_vars = ["pgDsId", "pgCat", "mysqlDsId", "mysqlCat", "mariaDsId", "mariaCat",
               "oracleDsId", "oracleCat", "snowDsId", "snowCat",
               "mongoDsId", "mongoCat", "csvDsId", "csvCat", "excelDsId", "excelCat"]

    items = [
        build_setup(base, "/actuator/health",
                    clear_vars=ds_vars + ["schemaName", "schemaId", "versionId",
                                          "realmId", "realmName", "streamId",
                                          "_allNodes", "_allLinks", "_ingestion_status"]),

        # ═══ PHASE 0: Create 8 DataSources ═══

        # DB types
        _db_ds("01a", "Postgres",  "",       "pgDsId",     "pgCat",     critical=True),
        _db_ds("01b", "MySQL",     "mysql",  "mysqlDsId",  "mysqlCat",  critical=False),
        _db_ds("01c", "MariaDB",   "maria",  "mariaDsId",  "mariaCat",  critical=False),
        _db_ds("01d", "Oracle",    "oracle", "oracleDsId", "oracleCat", critical=False),
        _db_ds("01e", "Snowflake", "snow",   "snowDsId",   "snowCat",   critical=False),

        # Mongo (needs shapeParseResult)
        req("01f Create Mongo DS", "POST", "/datasource",
            ["pm.test('01f Mongo 2xx', () => pm.expect(pm.response.code).to.be.oneOf([200,201,500]));",
             "let b={}; try{b=pm.response.json();}catch(e){}",
             "const d=b.dataSourceModel||b.data||b;",
             "if(d.id||d.sourceId) pm.collectionVariables.set('mongoDsId', String(d.id||d.sourceId));",
             "if(d.dataCatalogName) pm.collectionVariables.set('mongoCat', d.dataCatalogName);",
             "console.log('Mongo DS id='+(d.id||d.sourceId||'skipped'));"],
            base=base, body={"name": "x"},
            prerequest=[
                "const body = {",
                "  name: 'pm-flow-mongo-' + Date.now(),",
                "  driverType: 'MONGO',",
                "  dbHostName: pm.environment.get('mongo_dbHost') || '207.180.249.216',",
                "  dbPort: parseInt(pm.environment.get('mongo_dbPort') || '27018'),",
                "  databaseName: pm.environment.get('mongo_dbName') || 'datatypetesting_mongo',",
                "  dbUserName: pm.environment.get('mongo_dbUser') || 'quipu_admin',",
                "  dbPassword: pm.environment.get('mongo_dbPassword') || '',",
                "  aesRandomIV: pm.environment.get('mongo_aesRandomIV') || '',",
                "  dbSchema: pm.environment.get('mongo_dbSchema') || 'admin',",
                "  deleted: false,",
                "  shapeCypher: 'CREATE (g1:test {uri: \"$._id\", _id: \"$._id\"});',",
                "  shapeParseResult: {shape: {prefix: 'http://test.in/', nodes: [{label: 'test', prefix: 'http://test.in/', properties: [{jsonPath: '$._id', propertyName: '_id'}], uriProperty: '$._id', edgeShapes: []}], namespace: 'public', shapeType: 'CYPHER_DSL'}, constraints: []}",
                "};",
                "pm.request.body.raw = JSON.stringify(body);",
            ]),

        # CSV (S3 with files/columnDetails)
        req("01g Create CSV DS", "POST", "/datasource",
            ["pm.test('01g CSV 2xx', () => pm.expect(pm.response.code).to.be.oneOf([200,201,400]));",
             "let b={}; try{b=pm.response.json();}catch(e){}",
             "const d=b.dataSourceModel||b.data||b;",
             "if(d.id) pm.collectionVariables.set('csvDsId', String(d.id));",
             "if(d.dataCatalogName) pm.collectionVariables.set('csvCat', d.dataCatalogName);",
             "console.log('CSV DS id='+(d.id||'skipped'));"],
            base=base, body={"name": "x"},
            prerequest=[
                "const body = {",
                "  name: 'pm-flow-csv-' + Date.now(),",
                "  driverType: 'CSV',",
                "  bucket: pm.environment.get('s3_bucket') || 'quipu-api-tests',",
                "  key: pm.environment.get('s3_csv_key') || 'csvfiles',",
                "  region: pm.environment.get('s3_region') || 'ap-south-1',",
                "  accessKey: pm.environment.get('s3_access_key') || '',",
                "  secret: pm.environment.get('s3_secret_key') || '',",
                "  deleted: false,",
                "  files: [{key: pm.environment.get('s3_csv_file') || 'csvfiles/sample-data.csv', columnDetails: [",
                "    {name:'id',type:'INTEGER',nullable:false,primaryKey:true,uniqueKey:true},",
                "    {name:'name',type:'STRING',nullable:true,primaryKey:false,uniqueKey:false},",
                "    {name:'email',type:'STRING',nullable:true,primaryKey:false,uniqueKey:false},",
                "    {name:'age',type:'INTEGER',nullable:true,primaryKey:false,uniqueKey:false},",
                "    {name:'salary',type:'DOUBLE',nullable:true,primaryKey:false,uniqueKey:false},",
                "    {name:'department',type:'STRING',nullable:true,primaryKey:false,uniqueKey:false}",
                "  ]}]",
                "};",
                "pm.request.body.raw = JSON.stringify(body);",
            ]),

        # Excel (S3 with files/columnDetails)
        req("01h Create Excel DS", "POST", "/datasource",
            ["pm.test('01h Excel 2xx', () => pm.expect(pm.response.code).to.be.oneOf([200,201,400]));",
             "let b={}; try{b=pm.response.json();}catch(e){}",
             "const d=b.dataSourceModel||b.data||b;",
             "if(d.id) pm.collectionVariables.set('excelDsId', String(d.id));",
             "if(d.dataCatalogName) pm.collectionVariables.set('excelCat', d.dataCatalogName);",
             "console.log('Excel DS id='+(d.id||'skipped'));"],
            base=base, body={"name": "x"},
            prerequest=[
                "const body = {",
                "  name: 'pm-flow-excel-' + Date.now(),",
                "  driverType: 'EXCEL',",
                "  bucket: pm.environment.get('s3_bucket') || 'quipu-api-tests',",
                "  key: pm.environment.get('s3_excel_key') || 'excelfiles/Pharma_Drugs_V2.xlsx',",
                "  region: pm.environment.get('s3_region') || 'ap-south-1',",
                "  accessKey: pm.environment.get('s3_access_key') || '',",
                "  secret: pm.environment.get('s3_secret_key') || '',",
                "  deleted: false,",
                "  files: [{key: pm.environment.get('s3_excel_file') || 'datasource/pm-flow-excel/molecule_apis.csv', columnDetails: [",
                "    {name:'api_name',type:'STRING',nullable:true,primaryKey:false,uniqueKey:false},",
                "    {name:'molecular_weight',type:'DOUBLE',nullable:true,primaryKey:false,uniqueKey:false},",
                "    {name:'bioavailability',type:'STRING',nullable:true,primaryKey:false,uniqueKey:false}",
                "  ]}]",
                "};",
                "pm.request.body.raw = JSON.stringify(body);",
            ]),

        # ═══ PHASE 1: Schema → Version → Graph → Realm ═══

        req("02 Create Schema", "POST", "/schema",
            ["const code=pm.response.code;",
             "pm.test('02 Schema 2xx', () => { if(![200,201].includes(code)){pm.collectionVariables.set('_flow_failed','true');pm.collectionVariables.set('_flow_failed_at','02');} pm.expect(code).to.be.oneOf([200,201]); });",
             "let b={}; try{b=pm.response.json();}catch(e){}",
             "const d=b.schemaModel||b.data||b;",
             "if(d.name||d.schemaName) pm.collectionVariables.set('schemaName', d.name||d.schemaName);",
             "if(d.id||d.schemaId) pm.collectionVariables.set('schemaId', String(d.id||d.schemaId));"],
            base=base,
            body={"schemaName": "pm-flow-realm-schema-{{$timestamp}}", "description": "8-DS fabric"}),

        req("03 Create Version", "POST", "/versions/create?schemaName={{schemaName}}",
            ["const code=pm.response.code;",
             "pm.test('03 Version 2xx', () => { if(![200,201].includes(code)){pm.collectionVariables.set('_flow_failed','true');pm.collectionVariables.set('_flow_failed_at','03');} pm.expect(code).to.be.oneOf([200,201]); });",
             "let b={}; try{b=pm.response.json();}catch(e){}",
             "const d=b.data||b;",
             "if(d.id||d.versionId) pm.collectionVariables.set('versionId', String(d.id||d.versionId));"],
            base=base, body={"versionName": "v1"},
            prerequest=[
                "const ids=[];",
                "['pgDsId','mysqlDsId','mariaDsId','oracleDsId','snowDsId','mongoDsId','csvDsId','excelDsId'].forEach(k=>{const v=parseInt(pm.collectionVariables.get(k));if(v&&!isNaN(v))ids.push(v);});",
                "console.log('Version DSs: '+JSON.stringify(ids));",
                "pm.request.body.raw=JSON.stringify({versionName:'pm-flow-ver-'+Date.now(),description:'8-DS',dataSourceIds:ids,defaultVersion:true,latest:true,versionLocked:false,deleted:false});",
            ]),

        # Fetch metadata from each DS via transformation service → build entities
        req("04a Fetch PG Metadata", "POST", "/test-connection/metadata",
            ["pm.test('04a PG metadata reachable', () => pm.expect(pm.response.code).to.be.oneOf([200,201,400]));",
             "let tables = [];",
             "if(pm.response.code===200){",
             "  let b={}; try{b=pm.response.json();}catch(e){}",
             "  if(Array.isArray(b)) tables=b.map(t=>typeof t==='string'?t:(t.name||t.tableName||'')).filter(t=>t);",
             "  else if(b.tables) tables=b.tables.map(t=>typeof t==='string'?t:(t.name||t.tableName||'')).filter(t=>t);",
             "  else tables=Object.keys(b).filter(k=>k!=='error'&&k!=='status');",
             "}",
             "// Build entity nodes from table names",
             "const nodes = tables.slice(0,10).map((t,i) => ({id:'pg_'+i, label:t, type:'entity', prefix:'pg:', properties:{source:'POSTGRES'}}));",
             "pm.collectionVariables.set('_allNodes', JSON.stringify(nodes));",
             "pm.collectionVariables.set('_allLinks', '[]');",
             "console.log('PG tables: '+tables.slice(0,5).join(', ')+' → '+nodes.length+' entities');"],
            base="transform_base_url",
            body={"driverType": "{{driverType}}", "dbHostName": "{{dbHost}}", "dbPort": "{{dbPort}}",
                  "databaseName": "{{dbName}}", "dbUserName": "{{dbUser}}", "dbPassword": "{{dbPassword}}",
                  "aesRandomIV": "{{aesRandomIV}}", "dbSchema": "{{dbSchema}}", "driverClassName": "{{driverClassName}}"}),

        req("04b Fetch MySQL Metadata", "POST", "/test-connection/metadata",
            ["pm.test('04b MySQL metadata reachable', () => pm.expect(pm.response.code).to.be.oneOf([200,201,400]));",
             "if(pm.response.code===200){",
             "  let b={}; try{b=pm.response.json();}catch(e){}",
             "  let tables=[];",
             "  if(Array.isArray(b)) tables=b.map(t=>typeof t==='string'?t:(t.name||t.tableName||'')).filter(t=>t);",
             "  else if(b.tables) tables=b.tables.map(t=>typeof t==='string'?t:(t.name||t.tableName||'')).filter(t=>t);",
             "  const newNodes=tables.slice(0,10).map((t,i)=>({id:'mysql_'+i,label:t,type:'entity',prefix:'mysql:',properties:{source:'MYSQL'}}));",
             "  let all=[]; try{all=JSON.parse(pm.collectionVariables.get('_allNodes')||'[]');}catch(e){}",
             "  all=all.concat(newNodes);",
             "  pm.collectionVariables.set('_allNodes', JSON.stringify(all));",
             "  console.log('MySQL: '+newNodes.length+' entities, total: '+all.length);",
             "}"],
            base="transform_base_url",
            body={"driverType": "{{mysql_driverType}}", "dbHostName": "{{mysql_dbHost}}", "dbPort": "{{mysql_dbPort}}",
                  "databaseName": "{{mysql_dbName}}", "dbUserName": "{{mysql_dbUser}}", "dbPassword": "{{mysql_dbPassword}}",
                  "aesRandomIV": "{{mysql_aesRandomIV}}", "dbSchema": "{{mysql_dbSchema}}", "driverClassName": "{{mysql_driverClassName}}"}),

        req("04c Fetch MariaDB Metadata", "POST", "/test-connection/metadata",
            ["pm.test('04c Maria metadata reachable', () => pm.expect(pm.response.code).to.be.oneOf([200,201,400]));",
             "if(pm.response.code===200){",
             "  let b={}; try{b=pm.response.json();}catch(e){}",
             "  let tables=[];",
             "  if(Array.isArray(b)) tables=b.map(t=>typeof t==='string'?t:(t.name||t.tableName||'')).filter(t=>t);",
             "  else if(b.tables) tables=b.tables.map(t=>typeof t==='string'?t:(t.name||t.tableName||'')).filter(t=>t);",
             "  const newNodes=tables.slice(0,10).map((t,i)=>({id:'maria_'+i,label:t,type:'entity',prefix:'maria:',properties:{source:'MARIADB'}}));",
             "  let all=[]; try{all=JSON.parse(pm.collectionVariables.get('_allNodes')||'[]');}catch(e){}",
             "  all=all.concat(newNodes);",
             "  pm.collectionVariables.set('_allNodes', JSON.stringify(all));",
             "  console.log('MariaDB: '+newNodes.length+' entities, total: '+all.length);",
             "}"],
            base="transform_base_url",
            body={"driverType": "{{maria_driverType}}", "dbHostName": "{{maria_dbHost}}", "dbPort": "{{maria_dbPort}}",
                  "databaseName": "{{maria_dbName}}", "dbUserName": "{{maria_dbUser}}", "dbPassword": "{{maria_dbPassword}}",
                  "aesRandomIV": "{{maria_aesRandomIV}}", "dbSchema": "{{maria_dbSchema}}", "driverClassName": "{{maria_driverClassName}}"}),

        # CSV and Excel entities come from their columnDetails (already known)
        # Mongo entities come from shapeCypher (already defined)
        # Add them to the graph
        req("04d Add File+Mongo Entities", "GET", "/actuator/health",
            ["pm.test('04d health', () => pm.response.to.have.status(200));"],
            base=base,
            prerequest=[
                "// Add CSV entity node",
                "let all=[]; try{all=JSON.parse(pm.collectionVariables.get('_allNodes')||'[]');}catch(e){}",
                "all.push({id:'csv_0',label:'sample_data_csv',type:'entity',prefix:'csv:',properties:{source:'CSV',columns:'id,name,email,age,salary,department'}});",
                "// Add Excel entity node",
                "all.push({id:'excel_0',label:'pharma_drugs',type:'entity',prefix:'excel:',properties:{source:'EXCEL',columns:'api_name,molecular_weight,bioavailability'}});",
                "// Add Mongo entity node",
                "all.push({id:'mongo_0',label:'dt_mongo_group_1',type:'entity',prefix:'mongo:',properties:{source:'MONGO'}});",
                "pm.collectionVariables.set('_allNodes', JSON.stringify(all));",
                "console.log('Added CSV+Excel+Mongo entities, total: '+all.length);",
            ]),

        req("05 Save Schema Graph", "POST", "/schema-graph",
            ["pm.test('05 2xx', () => pm.expect(pm.response.code).to.be.oneOf([200,201,204]));",
             "console.log('Schema graph saved with entities from all DS types');"],
            base=base, body={"versionUri":"","nodes":[],"links":[]},
            prerequest=[
                "let n=[]; let l=[];",
                "try{n=JSON.parse(pm.collectionVariables.get('_allNodes')||'[]');}catch(e){}",
                "try{l=JSON.parse(pm.collectionVariables.get('_allLinks')||'[]');}catch(e){}",
                "console.log('Saving graph: '+n.length+' entities from PG+MySQL+MariaDB+CSV+Excel+Mongo');",
                "pm.request.body.raw=JSON.stringify({versionUri:pm.collectionVariables.get('schemaName')+'Version#v',nodes:n,links:l,schemaName:pm.collectionVariables.get('schemaName')});",
            ]),

        req("06 Create Realm", "POST", "/realm",
            ["const code=pm.response.code;",
             "pm.test('06 Realm 2xx', () => { if(![200,201].includes(code)){pm.collectionVariables.set('_flow_failed','true');pm.collectionVariables.set('_flow_failed_at','06');} pm.expect(code).to.be.oneOf([200,201]); });",
             "let b={}; try{b=pm.response.json();}catch(e){}",
             "const d=b.realmModel||b.data||b;",
             "if(d.id||d.realmId) pm.collectionVariables.set('realmId', String(d.id||d.realmId));",
             "if(d.name||d.realmName) pm.collectionVariables.set('realmName', d.name||d.realmName);",
             "console.log('Realm id='+(d.id||d.realmId));"],
            base=base, body={"name":"x"},
            prerequest=["pm.request.body.raw=JSON.stringify({name:'pm-flow-realm-'+Date.now(),description:'8-DS fabric',schemaName:pm.collectionVariables.get('schemaName'),versionId:parseInt(pm.collectionVariables.get('versionId'))});"]),

        # ═══ PHASE 2: Realm API Testing (12 endpoints) ═══

        req("07 List Realms", "GET", "/realm?page=0&size=20",
            ["pm.test('07 200|204', () => pm.expect(pm.response.code).to.be.oneOf([200,204]));"], base=base),
        req("08 Is Unique", "GET", "/realm/is-unique?realmName={{realmName}}",
            ["pm.test('08 200', () => pm.response.to.have.status(200));"], base=base),
        req("09 Get by ID", "GET", "/realm/{{realmId}}",
            ["pm.test('09 200', () => pm.response.to.have.status(200));",
             "let b={}; try{b=pm.response.json();}catch(e){} const d=b.realmModel||b.data||b;",
             "pm.test('09 id', () => pm.expect(String(d.id||d.realmId||'')).to.eql(pm.collectionVariables.get('realmId')));"],
            base=base),
        req("10 Get by Name", "GET", "/realm/by-name?realmName={{realmName}}",
            ["pm.test('10 200', () => pm.response.to.have.status(200));"], base=base),
        req("11 Get by Name LB", "GET", "/realm/by-name-lb?realmName={{realmName}}",
            ["pm.test('11 200', () => pm.response.to.have.status(200));"], base=base),
        req("12 All Realms", "GET", "/realm/all-realms-data",
            ["pm.test('12 200', () => pm.response.to.have.status(200));"], base=base),
        req("13 References", "GET", "/realm/references",
            ["pm.test('13 200|204', () => pm.expect(pm.response.code).to.be.oneOf([200,204]));"], base=base),
        req("14 Update", "PUT", "/realm",
            ["pm.test('14 200', () => pm.response.to.have.status(200));"],
            base=base, body={"id":0},
            prerequest=["pm.request.body.raw=JSON.stringify({id:parseInt(pm.collectionVariables.get('realmId')),name:pm.collectionVariables.get('realmName'),description:'Updated by FLOW'});"]),
        req("15 Verify Update", "GET", "/realm/{{realmId}}",
            ["pm.test('15 200', () => pm.response.to.have.status(200));",
             "let b={}; try{b=pm.response.json();}catch(e){} const d=b.realmModel||b.data||b;",
             "pm.test('15 updated', () => pm.expect(String(d.description||'')).to.include('Updated'));"],
            base=base),
        req("16 CDC Active", "GET", "/realm/cdc-active-realms",
            ["pm.test('16 200|204', () => pm.expect(pm.response.code).to.be.oneOf([200,204]));"], base=base),
        req("17 CDC by ID", "GET", "/realm/cdc-active/{{realmId}}",
            ["pm.test('17 200|204', () => pm.expect(pm.response.code).to.be.oneOf([200,204]));"], base=base),
        req("18 Update CDC", "PUT", "/realm/cdc-status/{{realmId}}?cdcStatus=true",
            ["pm.test('18 200|204', () => pm.expect(pm.response.code).to.be.oneOf([200,204]));"], base=base),

        # ═══ PHASE 3: Ingestion ═══

        req("19 Create Stream", "POST", "/atomicIngestStream/create-stream",
            ["pm.test('19 2xx', () => pm.expect(pm.response.code).to.be.oneOf([200,201]));",
             "let b={}; try{b=pm.response.json();}catch(e){} const d=b.data||b;",
             "if(d.id||d.streamId) pm.collectionVariables.set('streamId', String(d.id||d.streamId));"],
            base=base,
            body={"name":"pm-flow-stream-{{$timestamp}}","description":"FLOW","realmId":"{{realmId}}","streamType":"DBT-NODE","sqlQuery":"SELECT 1","cypherQuery":"","deleted":False}),
        req("20 Get Streams", "GET", "/atomicIngestStream/get-atomic-stream/{{realmId}}",
            ["pm.test('20 200', () => pm.response.to.have.status(200));"], base=base),
        req("21 Start", "POST", "/atomicIngestStream/atomic/running-status-change?streamRunning=true",
            ["pm.test('21 200', () => pm.expect(pm.response.code).to.be.oneOf([200,204]));"],
            base=base, body=[0],
            prerequest=["pm.request.body.raw=JSON.stringify([parseInt(pm.collectionVariables.get('streamId'))]);"]),
        req("22 Wait", "GET", "/atomicIngestStream/{{realmId}}/atomic/any-running",
            ["pm.test('22 200', () => pm.response.to.have.status(200));",
             "const s=pm.collectionVariables.get('_ingestion_status')||'UNKNOWN';",
             "pm.test('22 done', () => pm.expect(['COMPLETE','COMPLETED','STOPPED','TIMEOUT','false','UNKNOWN']).to.include(s));"],
            base=base,
            prerequest=[
                "const bu=pm.environment.get('app_base_url'),ri=pm.collectionVariables.get('realmId'),si=parseInt(pm.collectionVariables.get('streamId')),tk=pm.collectionVariables.get('access_token')||pm.environment.get('access_token'),ti=pm.environment.get('tenant_id');",
                "const mw=60000,iv=5000;let el=0;",
                "function p(d){pm.sendRequest({url:bu+'/atomicIngestStream/'+ri+'/atomic/any-running',method:'GET',header:{'Authorization':'Bearer '+tk,'X-TENANT-ID':ti}},(e,r)=>{let ru=true;try{ru=r.json();}catch(x){try{ru=r.text()==='true';}catch(y){}}",
                "if(ru===false||ru==='false'||el>=mw){pm.sendRequest({url:bu+'/atomic-ingestion-status/get-latest',method:'POST',header:{'Authorization':'Bearer '+tk,'X-TENANT-ID':ti,'Content-Type':'application/json'},body:{mode:'raw',raw:JSON.stringify([si])}},(e2,r2)=>{let st=el>=mw?'TIMEOUT':'COMPLETE';try{const a=r2.json();if(Array.isArray(a)&&a[0])st=a[0].statusMessage||st;}catch(x){}pm.collectionVariables.set('_ingestion_status',st);d();});}else{el+=iv;setTimeout(()=>p(d),iv);}});}",
                "p(()=>{});",
            ]),
        req("23 Status", "POST", "/atomic-ingestion-status/get-latest",
            ["pm.test('23 200', () => pm.response.to.have.status(200));"],
            base=base, body=[0],
            prerequest=["pm.request.body.raw=JSON.stringify([parseInt(pm.collectionVariables.get('streamId'))]);"]),
        req("24 Stop", "POST", "/atomicIngestStream/atomic/running-status-change?streamRunning=false",
            ["pm.test('24 200', () => pm.expect(pm.response.code).to.be.oneOf([200,204]));"],
            base=base, body=[0],
            prerequest=["pm.request.body.raw=JSON.stringify([parseInt(pm.collectionVariables.get('streamId'))]);"]),

        # ═══ PHASE 4: Cleanup ═══

        req("25 Del Realm", "DELETE", "/realm/{{realmId}}?permanent=true",
            ["pm.test('25 2xx', () => pm.expect(pm.response.code).to.be.oneOf([200,204]));"], base=base),
        req("26 Verify Del", "GET", "/realm/{{realmId}}",
            ["pm.test('26 gone', () => pm.expect(pm.response.code).to.be.oneOf([400,404,500]));"], base=base),
        req("27 Del Graph", "DELETE", "/schema-graph?prefix={{schemaName}}",
            ["pm.test('27 ok', () => pm.expect(pm.response.code).to.be.oneOf([200,204,404]));"], base=base),
        req("28 Del Version", "DELETE", "/versions/delete?versionId={{versionId}}",
            ["pm.test('28 ok', () => pm.expect(pm.response.code).to.be.oneOf([200,204,404]));"], base=base),
        req("29 Del Schema", "DELETE", "/schema?schemaName={{schemaName}}",
            ["pm.test('29 ok', () => pm.expect(pm.response.code).to.be.oneOf([200,204,404]));"], base=base),
        req("30 Del PG", "DELETE", "/datasource/{{pgDsId}}",
            ["pm.test('30 ok', () => pm.expect(pm.response.code).to.be.oneOf([200,204,400,404]));"], base=base),
        req("31 Del MySQL", "DELETE", "/datasource/{{mysqlDsId}}",
            ["pm.test('31 ok', () => pm.expect(pm.response.code).to.be.oneOf([200,204,400,404]));"], base=base),
        req("32 Del Maria", "DELETE", "/datasource/{{mariaDsId}}",
            ["pm.test('32 ok', () => pm.expect(pm.response.code).to.be.oneOf([200,204,400,404]));"], base=base),
        req("33 Del Oracle", "DELETE", "/datasource/{{oracleDsId}}",
            ["pm.test('33 ok', () => pm.expect(pm.response.code).to.be.oneOf([200,204,400,404]));"], base=base),
        req("34 Del Snow", "DELETE", "/datasource/{{snowDsId}}",
            ["pm.test('34 ok', () => pm.expect(pm.response.code).to.be.oneOf([200,204,400,404]));"], base=base),
        req("35 Del Mongo", "DELETE", "/datasource/{{mongoDsId}}",
            ["pm.test('35 ok', () => pm.expect(pm.response.code).to.be.oneOf([200,204,400,404]));"], base=base),
        req("36 Del CSV", "DELETE", "/datasource/{{csvDsId}}",
            ["pm.test('36 ok', () => pm.expect(pm.response.code).to.be.oneOf([200,204,400,404]));"], base=base),
        req("37 Del Excel", "DELETE", "/datasource/{{excelDsId}}",
            ["pm.test('37 ok', () => pm.expect(pm.response.code).to.be.oneOf([200,204,400,404]));"], base=base),

        req("99 Teardown", "DELETE", "/realm/{{realmId}}?permanent=true",
            ["pm.test('99 teardown', () => pm.expect(pm.response.code).to.be.oneOf([200,204,400,404]));",
             "pm.collectionVariables.unset('_flow_failed'); pm.collectionVariables.unset('_flow_failed_at');"],
            base=base, skip_on_fail=False),
    ]

    col = build_collection(
        name="FLOW - Realm CRUD (8-DS Fabric)",
        description="Full realm with 8 datasource types: Postgres, MySQL, MariaDB, Oracle, Snowflake, Mongo, CSV, Excel.\n\n"
                    "Requires env-vars per DS type + S3 config for CSV/Excel.",
        folder_name="Realm CRUD (8-DS)",
        items=items,
        extra_variables=[{"key": k, "value": "", "type": "string"} for k in
            ds_vars + ["schemaName", "schemaId", "versionId", "realmId", "realmName",
                       "streamId", "_allNodes", "_allLinks", "_ingestion_status"]]
    )
    return write_flow("FLOW-Realm-CRUD.postman_collection.json", col)
