#!/usr/bin/env python
"""Build the test-secrets .env from local configs and push it (plus environments + db-configs) to S3.

The Jenkins app-service pipeline (Setup API Tests stage) pulls creds at test time from:
    s3://<bucket>/config/secrets/<env>.secrets.env   -> parsed into `--env-var key=val`
These secrets are gitignored (never checked in), so they live only in S3. This utility:
  1. Flattens config/db-configs/*.json into the flat env-vars the flows expect
     (postgres unprefixed; mysql_/maria_/oracle_/snow_/mongo_ prefixed; s3_* from csv/excel),
  2. adds the Keycloak creds (client_secret / test_username / test_password),
  3. writes config/secrets/<env>.secrets.env,
  4. uploads it (and, with --all, environments/ + db-configs/) to S3.

NOTE: multi-line values (mongo shapeCypher) are EXCLUDED — the pipeline parses the .env line by
line (IFS='='), so a newline would corrupt it. The mongo shapeCypher is embedded in the flow instead.

Usage:
  python scripts/push_test_secrets.py --env dev --user karthik --password karthik12 [--push] [--all]
  python scripts/push_test_secrets.py --env dev --dry-run           # print, don't write/upload
"""
import argparse, json, os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CFG = os.path.join(ROOT, "config", "db-configs")

# datasource config -> env-var prefix the flow templates expect ({{prefix_dbHost}} etc.)
DB_PREFIX = {"postgres": "", "mysql": "mysql_", "mariadb": "maria_",
             "oracle": "oracle_", "snowflake": "snow_", "mongo": "mongo_"}
DB_FIELDS = ["driverType", "dbHost", "dbPort", "dbName", "dbUser", "dbPassword",
             "dbSchema", "driverClassName", "aesRandomIV"]   # NOTE: no shapeCypher / columns


def load(name):
    p = os.path.join(CFG, f"{name}.json")
    return json.load(open(p, encoding="utf-8")) if os.path.exists(p) else None


def build_env(user, password, client_secret):
    lines = ["# Auto-generated by scripts/push_test_secrets.py — do NOT commit (gitignored).",
             "# Consumed by the app-service Jenkins pipeline (Run API Flow Tests) as --env-var.",
             "", "# --- Keycloak ---",
             f"client_secret={client_secret}", f"test_username={user}", f"test_password={password}",
             "", "# --- Datasource creds (flat, prefixed to match the flow template vars) ---"]
    for name, pfx in DB_PREFIX.items():
        d = load(f"{name}-datatype")
        if not d:
            continue
        for k in DB_FIELDS:
            v = d.get(k)
            if v is not None and "\n" not in str(v):
                lines.append(f"{pfx}{k}={v}")
    csv, xls = load("csv-datatype"), load("excel-datatype")
    if csv:
        lines += ["", "# --- S3 (CSV + Excel datasources) ---",
                  f"s3_access_key={csv['accessKey']}", f"s3_secret_key={csv['secret']}",
                  f"s3_region={csv.get('region','ap-south-1')}",
                  f"s3_bucket={csv['bucket']}", f"s3_csv_bucket={csv['bucket']}",
                  f"s3_csv_key={csv['key']}", f"s3_csv_file={csv['file']}"]
    if xls:
        lines += [f"s3_excel_bucket={xls['bucket']}", f"s3_excel_key={xls['key']}",
                  f"s3_excel_file={xls['file']}"]
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--env", default="dev", help="secrets file name -> <env>.secrets.env (pipeline falls back to dev)")
    ap.add_argument("--user", default=os.environ.get("TEST_USERNAME", "karthik"))
    ap.add_argument("--password", default=os.environ.get("TEST_PASSWORD", "karthik12"))
    ap.add_argument("--secret", default=os.environ.get("CLIENT_SECRET", "h7rKFLYmYX407iWrgcDJPx9N2L04V4So"))
    ap.add_argument("--bucket", default=os.environ.get("S3_TEST_BUCKET", "quipu-api-tests"))
    ap.add_argument("--push", action="store_true", help="upload the secrets .env to S3")
    ap.add_argument("--all", action="store_true", help="also sync environments/ and db-configs/ to S3")
    ap.add_argument("--dry-run", action="store_true", help="print only; do not write or upload")
    args = ap.parse_args()

    content = build_env(args.user, args.password, args.secret)
    masked = "\n".join(l if "=" not in l or not any(s in l.lower() for s in ("secret", "password", "access_key"))
                       else l.split("=")[0] + "=***" for l in content.splitlines())
    print(f"=== config/secrets/{args.env}.secrets.env ({len(content.splitlines())} lines) ===")
    print(masked)
    if args.dry_run:
        print("\n(dry-run: nothing written or uploaded)"); return

    sec_dir = os.path.join(ROOT, "config", "secrets")
    os.makedirs(sec_dir, exist_ok=True)
    path = os.path.join(sec_dir, f"{args.env}.secrets.env")
    open(path, "w", encoding="utf-8").write(content)
    print(f"\nwrote {path}")

    if args.push or args.all:
        dst = f"s3://{args.bucket}/config/secrets/{args.env}.secrets.env"
        subprocess.run(["aws", "s3", "cp", path, dst], check=True)
        print(f"uploaded -> {dst}")
    if args.all:
        subprocess.run(["aws", "s3", "sync", os.path.join(ROOT, "environments"),
                        f"s3://{args.bucket}/config/environments/", "--exclude", "*",
                        "--include", "*.postman_environment.json"], check=True)
        subprocess.run(["aws", "s3", "sync", CFG, f"s3://{args.bucket}/config/db-configs/",
                        "--exclude", "*", "--include", "*.json"], check=True)
        print("synced environments/ + db-configs/ to S3")


if __name__ == "__main__":
    main()
